"""Per-section widget color scheme generation — a direct line-for-line port
of chatty/src/lib/color-contrast.ts's hexToRgb/getOnColor/hexToHsl/
hslToHex/generateColorScheme, so a scheme generated here (via the MCP
server) and one generated by the dashboard's own "Auto-generate" button
produce byte-identical hex values for the same seed color. If that
TypeScript file's algorithm ever changes, this must change with it.
"""

from __future__ import annotations

import re
from typing import Optional

_HEX_RE = re.compile(r"^#[0-9a-fA-F]{3,8}$")


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    clean = hex_color.replace("#", "").strip()
    full = "".join(c * 2 for c in clean) if len(clean) == 3 else clean
    try:
        num = int(full, 16)
    except ValueError:
        return (249, 115, 22)  # fallback: brand orange, matches the TS default
    if len(full) != 6:
        return (249, 115, 22)
    return ((num >> 16) & 255, (num >> 8) & 255, num & 255)


def _relative_luminance(r: int, g: int, b: int) -> float:
    def chan(c: int) -> float:
        v = c / 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    rs, gs, bs = chan(r), chan(g), chan(b)
    return 0.2126 * rs + 0.7152 * gs + 0.0722 * bs


def get_on_color(background_hex: str) -> str:
    r, g, b = hex_to_rgb(background_hex)
    bg_lum = _relative_luminance(r, g, b)
    return "#111827" if bg_lum > 0.55 else "#ffffff"


def _hex_to_hsl(hex_color: str) -> tuple[float, float, float]:
    r8, g8, b8 = hex_to_rgb(hex_color)
    r, g, b = r8 / 255, g8 / 255, b8 / 255
    mx, mn = max(r, g, b), min(r, g, b)
    l = (mx + mn) / 2
    if mx == mn:
        return (0.0, 0.0, l * 100)
    d = mx - mn
    s = d / (2 - mx - mn) if l > 0.5 else d / (mx + mn)
    if mx == r:
        h = ((g - b) / d + (6 if g < b else 0)) / 6
    elif mx == g:
        h = ((b - r) / d + 2) / 6
    else:
        h = ((r - g) / d + 4) / 6
    return (h * 360, s * 100, l * 100)


def _hsl_to_hex(h: float, s: float, l: float) -> str:
    S, L = s / 100, l / 100
    c = (1 - abs(2 * L - 1)) * S
    hp = ((h % 360) + 360) % 360 / 60
    x = c * (1 - abs((hp % 2) - 1))
    if hp < 1:
        r1, g1, b1 = c, x, 0.0
    elif hp < 2:
        r1, g1, b1 = x, c, 0.0
    elif hp < 3:
        r1, g1, b1 = 0.0, c, x
    elif hp < 4:
        r1, g1, b1 = 0.0, x, c
    elif hp < 5:
        r1, g1, b1 = x, 0.0, c
    else:
        r1, g1, b1 = c, 0.0, x
    m = L - c / 2

    def to_hex(v: float) -> str:
        return format(round((v + m) * 255), "02x")
    return f"#{to_hex(r1)}{to_hex(g1)}{to_hex(b1)}"


def generate_color_scheme(seed_hex: str) -> dict[str, dict[str, str]]:
    """Derives a full 6-section color scheme from one seed color — same hue
    throughout, lightness/saturation shifted per surface, text/icon colors
    computed against each section's own actual background. Mirrors
    generateColorScheme in chatty/src/lib/color-contrast.ts exactly."""
    h, s, _l = _hex_to_hsl(seed_hex)
    solid = seed_hex
    solid_text = get_on_color(solid)
    soft_bg = _hsl_to_hex(h, min(s, 45) * 0.5, 95)
    soft_text = _hsl_to_hex(h, min(s, 45) * 0.6, 22)
    return {
        "header": {"bg": solid, "text": solid_text},
        "botBubble": {"bg": soft_bg, "text": soft_text},
        "userBubble": {"bg": solid, "text": solid_text},
        "inputBar": {
            "bg": _hsl_to_hex(h, min(s, 30) * 0.35, 97.5),
            "text": soft_text,
            "icon": _hsl_to_hex(h, min(s, 50), 45),
        },
        "sendBtn": {"bg": solid, "text": solid_text},
        "launcher": {"bg": solid, "text": solid_text},
    }


def safe_hex(value: Optional[str]) -> Optional[str]:
    return value if value and _HEX_RE.match(value) else None
