export const GOOGLE_FONTS: { value: string | null; label: string }[] = [
  { value: null, label: "Design default" },
  { value: "Inter", label: "Inter" },
  { value: "Roboto", label: "Roboto" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Lato", label: "Lato" },
  { value: "Poppins", label: "Poppins" },
  { value: "Nunito", label: "Nunito" },
  { value: "Work Sans", label: "Work Sans" },
  { value: "DM Sans", label: "DM Sans" },
  { value: "Manrope", label: "Manrope" },
  { value: "Sora", label: "Sora" },
  { value: "Outfit", label: "Outfit" },
  { value: "Space Grotesk", label: "Space Grotesk" },
  { value: "Plus Jakarta Sans", label: "Plus Jakarta Sans" },
  { value: "Quicksand", label: "Quicksand" },
  { value: "Rubik", label: "Rubik" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Merriweather", label: "Merriweather" },
  { value: "Lora", label: "Lora" },
  { value: "IBM Plex Mono", label: "IBM Plex Mono (monospace)" },
];

export const LOCALE_TEXTS: Record<string, Record<string, string>> = {
  EN: {
    overview: "Overview",
    customizer: "Customizer",
    knowledge_base: "Knowledge Base",
    playground: "Playground",
    leads: "Leads",
    analytics: "Analytics",
    integrations: "Embed & Integrate",
    settings: "Agent Settings",
    meetings: "Meetings",
    notifications: "Notifications",
    audit_log: "Audit Log",
    training_data: "Training Data",
    setup_wizard: "AI Assistant Setup Wizard",
    welcome: "Hi! Would you like to train the assistant using your business data?",
    yes: "Yes",
    no: "No",
    supported_sources: "Supported Sources",
    optional_integrations: "Optional Integrations",
    processing: "Processing your files...",
    training_completed: "Training completed successfully.",
    custom_instructions_q: "Do you have any custom instructions, rules, policies, or response guidelines?",
    save_instructions: "Save Instructions",
    instructions_saved: "Instructions received and saved successfully.",
    enable_lead_extraction: "Would you like to enable Lead Extraction?",
    lead_fields_q: "Please specify which lead fields should be captured.",
    lead_configured: "Lead extraction configured successfully.",
    schedule_meetings_q: "Would you like the assistant to schedule meetings with leads?",
    timezone_confirm: "Please confirm country and timezone:",
    calendar_integration_q: "Please connect your calendar:",
    calendar_connected: "Calendar connected successfully.",
    meeting_provider_q: "Please select meeting providers:",
    provider_configured: "Meeting provider configured successfully.",
    scheduling_rules: "Scheduling Rules Checklist:",
    confirm_rules: "Review and Proceed",
    notifications_setup: "Setup notification channels when a meeting is booked:",
    notify_client: "Notify Client via Email & Push",
    notify_admin: "Notify Administrator via Email & Push",
    setup_completed: "Setup completed successfully.",
    go_to_admin: "Open Admin Panel",
    back: "Back",
    next: "Next",
    skip: "Skip Setup",
    language: "Language",
    timezone: "Timezone",
    country: "Country",
  },
  ES: {
    overview: "Vista General",
    customizer: "Personalizador",
    knowledge_base: "Base de Conocimientos",
    playground: "Área de Pruebas",
    leads: "Clientes Potenciales",
    analytics: "Analítica",
    integrations: "Incrustar e Integrar",
    settings: "Configuración del Agente",
    meetings: "Reuniones",
    notifications: "Notificaciones",
    audit_log: "Registro de Auditoría",
    training_data: "Datos de Entrenamiento",
    setup_wizard: "Asistente de Configuración de IA",
    welcome: "¿Le gustaría entrenar al asistente con los datos de su negocio?",
    yes: "Sí",
    no: "No",
    supported_sources: "Fuentes Soportadas",
    optional_integrations: "Integraciones Opcionales",
    processing: "Procesando sus archivos...",
    training_completed: "Entrenamiento completado con éxito.",
    custom_instructions_q: "¿Tiene alguna instrucción personalizada, regla, política o guía de respuesta?",
    save_instructions: "Guardar Instrucciones",
    instructions_saved: "Instrucciones recibidas y guardadas con éxito.",
    enable_lead_extraction: "¿Le gustaría activar la Extracción de Clientes Potenciales?",
    lead_fields_q: "Por favor, especifique qué campos de clientes potenciales capturar.",
    lead_configured: "Extracción de clientes potenciales configurada con éxito.",
    schedule_meetings_q: "¿Le gustaría que el asistente programe reuniones con clientes potenciales?",
    timezone_confirm: "Por favor, confirme país y zona horaria:",
    calendar_integration_q: "Por favor, conecte su calendario:",
    calendar_connected: "Calendario conectado con éxito.",
    meeting_provider_q: "Por favor, seleccione proveedores de reuniones:",
    provider_configured: "Proveedor de reuniones configurado con éxito.",
    scheduling_rules: "Lista de Reglas de Programación:",
    confirm_rules: "Revisar y Continuar",
    notifications_setup: "Configure los canales de notificación cuando se reserve una reunión:",
    notify_client: "Notificar al Cliente por Correo y Push",
    notify_admin: "Notificar al Administrador por Correo y Push",
    setup_completed: "Configuración completada con éxito.",
    go_to_admin: "Abrir Panel de Administración",
    back: "Atrás",
    next: "Siguiente",
    skip: "Omitir Configuración",
    language: "Idioma",
    timezone: "Zona Horaria",
    country: "País",
  },
  FR: {
    overview: "Vue d'ensemble",
    customizer: "Personnalisateur",
    knowledge_base: "Base de Connaissances",
    playground: "Espace d'essai",
    leads: "Prospects",
    analytics: "Analytiques",
    integrations: "Intégrer le code",
    settings: "Paramètres de l'agent",
    meetings: "Réunions",
    notifications: "Notifications",
    audit_log: "Journal d'audit",
    training_data: "Données d'entraînement",
    setup_wizard: "Assistant de Configuration IA",
    welcome: "Souhaitez-vous entraîner l'assistant en utilisant les données de votre entreprise?",
    yes: "Oui",
    no: "Non",
    supported_sources: "Sources Supportées",
    optional_integrations: "Intégrations Optionnelles",
    processing: "Traitement de vos fichiers...",
    training_completed: "Entraînement terminé avec succès.",
    custom_instructions_q: "Avez-vous des instructions personnalisées, des règles ou des directives de réponse?",
    save_instructions: "Enregistrer les Instructions",
    instructions_saved: "Instructions reçues et enregistrées avec succès.",
    enable_lead_extraction: "Souhaitez-vous activer l'extraction de prospects?",
    lead_fields_q: "Veuillez spécifier quels champs de prospects doivent être capturés.",
    lead_configured: "Extraction de prospects configurée avec succès.",
    schedule_meetings_q: "Souhaitez-vous que l'assistant planifie des réunions avec les prospects?",
    timezone_confirm: "Veuillez confirmer le pays et le fuseau horaire:",
    calendar_integration_q: "Veuillez connecter votre calendrier:",
    calendar_connected: "Calendrier connecté avec succès.",
    meeting_provider_q: "Veuillez sélectionner les fournisseurs de réunion:",
    provider_configured: "Fournisseur de réunion configuré avec succès.",
    scheduling_rules: "Liste des règles de planification:",
    confirm_rules: "Vérifier et Continuer",
    notifications_setup: "Configurer les canaux de notification lors de la réservation d'une réunion:",
    notify_client: "Notifier le client par e-mail et push",
    notify_admin: "Notifier l'administrateur par e-mail et push",
    setup_completed: "Configuration terminée avec succès.",
    go_to_admin: "Ouvrir le panneau d'administration",
    back: "Retour",
    next: "Suivant",
    skip: "Ignorer la configuration",
    language: "Langue",
    timezone: "Fuseau Horaire",
    country: "Pays",
  },
  DE: {
    overview: "Übersicht",
    customizer: "Anpasser",
    knowledge_base: "Wissensdatenbank",
    playground: "Spielwiese",
    leads: "Kontakte",
    analytics: "Analysen",
    integrations: "Einbetten & Integrieren",
    settings: "Agenten-Einstellungen",
    meetings: "Besprechungen",
    notifications: "Benachrichtigungen",
    audit_log: "Audit-Protokoll",
    training_data: "Trainingsdaten",
    setup_wizard: "KI-Assistent Onboarding-Assistent",
    welcome: "Möchten Sie den Assistenten mit Ihren Geschäftsdaten trainieren?",
    yes: "Ja",
    no: "Nein",
    supported_sources: "Unterstützte Quellen",
    optional_integrations: "Optionale Integrationen",
    processing: "Ihre Dateien werden verarbeitet...",
    training_completed: "Training erfolgreich abgeschlossen.",
    custom_instructions_q: "Haben Sie benutzerdefinierte Anweisungen, Regeln, Richtlinien oder Antwortrichtlinien?",
    save_instructions: "Anweisungen Speichern",
    instructions_saved: "Anweisungen erfolgreich empfangen und gespeichert.",
    enable_lead_extraction: "Möchten Sie die Lead-Extraktion aktivieren?",
    lead_fields_q: "Bitte geben Sie an, welche Lead-Felder erfasst werden sollen.",
    lead_configured: "Lead-Extraktion erfolgreich konfiguriert.",
    schedule_meetings_q: "Möchten Sie, dass der Assistent Termine mit Leads vereinbart?",
    timezone_confirm: "Bitte bestätigen Sie Land und Zeitzone:",
    calendar_integration_q: "Bitte verbinden Sie Ihren Kalender:",
    calendar_connected: "Kalender erfolgreich verbunden.",
    meeting_provider_q: "Bitte wählen Sie Meeting-Anbieter aus:",
    provider_configured: "Meeting-Anbieter erfolgreich konfiguriert.",
    scheduling_rules: "Checkliste für Planungsregeln:",
    confirm_rules: "Überprüfen und fortfahren",
    notifications_setup: "Benachrichtigungskanäle einrichten, wenn ein Termin gebucht wird:",
    notify_client: "Client per E-Mail & Push benachrichtigen",
    notify_admin: "Administrator per E-Mail & Push benachrichtigen",
    setup_completed: "Einrichtung erfolgreich abgeschlossen.",
    go_to_admin: "Admin-Panel öffnen",
    back: "Zurück",
    next: "Weiter",
    skip: "Einrichtung überspringen",
    language: "Sprache",
    timezone: "Zeitzone",
    country: "Land",
  },
  IT: {
    overview: "Panoramica",
    customizer: "Personalizzatore",
    knowledge_base: "Database Conoscenza",
    playground: "Area di Prova",
    leads: "Contatti",
    analytics: "Analisi",
    integrations: "Incorpora e Integra",
    settings: "Impostazioni Agente",
    meetings: "Riunioni",
    notifications: "Notifiche",
    audit_log: "Registro di Audit",
    training_data: "Dati di Addestramento",
    setup_wizard: "Configurazione Guidata Assistente IA",
    welcome: "Vorresti addestrare l'assistente usando i tuoi dati aziendali?",
    yes: "Sì",
    no: "No",
    supported_sources: "Fonti Supportate",
    optional_integrations: "Integrazioni Opzionali",
    processing: "Elaborazione dei file in corso...",
    training_completed: "Addestramento completato con successo.",
    custom_instructions_q: "Hai istruzioni personalizzate, regole, politiche o linee guida per le risposte?",
    save_instructions: "Salva Istruzioni",
    instructions_saved: "Istruzioni ricevute e salvate con successo.",
    enable_lead_extraction: "Vorresti abilitare l'estrazione dei contatti?",
    lead_fields_q: "Specifica quali campi dei contatti catturare.",
    lead_configured: "Estrazione contatti configurata con successo.",
    schedule_meetings_q: "Vorresti che l'assistente pianifichi riunioni con i contatti?",
    timezone_confirm: "Conferma paese e fuso orario:",
    calendar_integration_q: "Connetti il tuo calendario:",
    calendar_connected: "Calendario connesso con successo.",
    meeting_provider_q: "Seleziona i provider per le riunioni:",
    provider_configured: "Provider di riunioni configurato con successo.",
    scheduling_rules: "Checklist Regole di Pianificazione:",
    confirm_rules: "Rivedi e Procedi",
    notifications_setup: "Configura i canali di notifica alla prenotazione di una riunione:",
    notify_client: "Notifica Cliente via Email e Push",
    notify_admin: "Notifica Amministratore via Email e Push",
    setup_completed: "Configurazione completata con successo.",
    go_to_admin: "Apri Pannello Amministratore",
    back: "Indietro",
    next: "Avanti",
    skip: "Salta Configurazione",
    language: "Lingua",
    timezone: "Fuso Orario",
    country: "Paese",
  },
};

export const PLAN_LABELS: Record<string, string> = {
  free: "Free",
  chatty_hobby: "Hobby",
  chatty_standard: "Standard",
  chatty_business: "Business",
};

export const MAX_BOTS_BY_PLAN: Record<string, number> = {
  free: 1,
  chatty_hobby: 1,
  chatty_standard: 3,
  chatty_business: 5,
};
